---
- hosts: vps
  tasks:
    - name: Listing all groups
      shell: groups >> groups.txt
    - name: Create a login user
      user:
        name: Jan_Kowalski
        #password = secret
        #usemkpasswd --method=sha-512 to generate password, below is sha for 'admin'
        #On Debian/Ubuntu systems, mkpasswd likely exists, but if not, it's part of the whois package: sudo apt-get install -y whois
        password: '$6$F4NWXRFtSdCi8$DsB5vvMJYusQhSbvGXrYDXL6Xj37MUuqFCd4dGXdKd6NyxT3lpdELN07/Kpo7EjjWnm9zusFg/LLFv6oc.ynu/'
        groups: docker, sudo   
        state: present
        shell: /bin/bash       
        home: /home/Jan_Kowalski  # Defaults to /home/<username>
    - name: Installing git
      apt: 
        name: git
        update_cache: yes
        state: latest
