---
- name: Wprowadzenie. Tworzymy plik z zawartoscia
  hosts: all
  become: true
  tasks:
    - name: print Hello World
      shell: echo "Hello World!" >> hello
    - name: Check memory size
      shell: grep MemTotal /proc/meminfo >> memorySize
    - assert:
        that:
          - ansible_memory_mb.real.total >= 512

    - name: Install add-apt-repostory
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default

