---
- name: Wprowadzenie. Tworzymy plik z zawartoscia
  hosts: all
  become: true
  tasks:
    - name: print Hello World
      shell: echo "Hello World!" >> hello
    - name: Check memory size
      shell: grep MemTotal /proc/meminfo >> memorySize
    - assert:
        that:
          - ansible_memory_mb.real.total >= 512
